"""Machine-readable schema manifest of the market-database contract.

The manifest (``schema_manifest.json``, committed next to this module)
describes the subset of ``iaew-marktdaten.db`` that the framework reads.
It is generated by inspecting the real database and is the contract that

* the synthetic generator reproduces exactly (same tables, columns, types),
* the validator checks any candidate database against,
* CI uses when the real database is unavailable.

Regenerate after a real-schema change with::

    uv run python -m hybrid_vpp.data.schema_manifest
"""

from __future__ import annotations

import json
import logging
import os
import sqlite3
from pathlib import Path

log = logging.getLogger(__name__)

SCHEMA_VERSION = "1.0"
MANIFEST_PATH = Path(__file__).parent / "schema_manifest.json"

#: tables (and the columns) the framework reads — the drop-in contract.
#: "required" tables must exist with all listed columns; wide IDA tables list
#: only the identifying column (product columns are validated by pattern).
REQUIRED_TABLES = {
    "day_ahead_prices": ["index", "price_eur_per_mwh"],
    "pan_european_ida1_prices": ["Delivery day"],
    "pan_european_ida2_prices": ["Delivery day"],
    "pan_european_ida3_prices": ["Delivery day"],
    "intraday_continuous_indices": [
        "Time",
        "IndexName",
        "TimeResolution",
        "IndexPrice",
        "IndexVolume",
        "DeliveryEnd",
        "Currency",
        "VolumeUnit",
    ],
    "netztransparenz_nrv_saldo_reBAP_Qualitaetsgesichert": [
        "Date",
        "reBAP unterdeckt",
        "reBAP ueberdeckt",
    ],
    "imbalance_prices": ["index", "Long", "Short"],
    "generation": [
        "index",
        "Wind Onshore_Actual Aggregated",
        "Wind Offshore_Actual Aggregated",
        "Solar_Actual Aggregated",
    ],
    "wind_and_solar_forecast": ["index", "Solar", "Wind Offshore", "Wind Onshore"],
    "intraday_wind_and_solar_forecast": ["index", "Solar", "Wind Offshore", "Wind Onshore"],
}

OPTIONAL_TABLES = {
    "intraday_continuous_statistics": [
        "deliverystart",
        "deliveryend",
        "lowprice",
        "highprice",
        "lastprice",
        "weightedaverageprice",
        "volumebuy",
        "volumesell",
    ],
}


def generate_manifest(db_path: Path) -> dict:
    """Inspect a database and produce the manifest for the required subset."""
    manifest: dict = {
        "schema_version": SCHEMA_VERSION,
        "source": db_path.name,  # never record private absolute paths
        "timezone_conventions": {
            "day_ahead_prices": "naive Europe/Berlin (autumn DST hour duplicated, "
            "first occurrence = CEST, in row order)",
            "pan_european_ida*_prices": "local delivery day + local product columns "
            "'hour H qQ' incl. 'hour 3a/3b' DST columns",
            "intraday_continuous_indices": "naive UTC",
            "netztransparenz_*": "naive UTC (explicit Zeitzone column)",
            "imbalance_prices": "naive Europe/Berlin",
            "generation/forecast tables": "naive Europe/Berlin",
        },
        "units": {"prices": "EUR/MWh", "volumes": "MWh", "power": "MW"},
        "tables": {},
    }
    with sqlite3.connect(f"file:{db_path}?mode=ro", uri=True) as con:
        for table, required_cols in {**REQUIRED_TABLES, **OPTIONAL_TABLES}.items():
            info = con.execute(f'PRAGMA table_info("{table}")').fetchall()
            if not info:
                log.warning("table %s missing in %s", table, db_path)
                continue
            columns = {row[1]: row[2] or "TEXT" for row in info}
            missing = [c for c in required_cols if c not in columns]
            if missing:
                raise ValueError(f"{table} lacks required columns {missing}")
            indexes = [row[1] for row in con.execute(f'PRAGMA index_list("{table}")').fetchall()]
            manifest["tables"][table] = {
                "columns": columns,
                "required_columns": required_cols,
                "optional": table in OPTIONAL_TABLES,
                "indexes": indexes,
            }
    return manifest


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def validate_against_manifest(db_path: Path, manifest: dict | None = None) -> list[str]:
    """Return a list of problems (empty = schema-compatible)."""
    manifest = manifest or load_manifest()
    problems: list[str] = []
    try:
        con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    except sqlite3.Error as exc:
        return [f"cannot open {db_path}: {exc}"]
    with con:
        for table, spec in manifest["tables"].items():
            info = con.execute(f'PRAGMA table_info("{table}")').fetchall()
            if not info:
                if not spec.get("optional"):
                    problems.append(f"missing table {table}")
                continue
            columns = {row[1] for row in info}
            for col in spec["required_columns"]:
                if col not in columns:
                    problems.append(f"{table}: missing column {col!r}")
    return problems


# --------------------------------------------------------------------------
# CONFIG — edit and run as a module (no CLI flags by design)
# --------------------------------------------------------------------------
DATABASE_PATH = Path(os.environ.get("MARKET_DATABASE_PATH", "iaew-marktdaten.db"))

if __name__ == "__main__":
    from hybrid_vpp.config.models import _load_env_files

    logging.basicConfig(level=logging.INFO)
    _load_env_files()
    DATABASE_PATH = Path(os.environ.get("MARKET_DATABASE_PATH", str(DATABASE_PATH)))
    manifest = generate_manifest(DATABASE_PATH)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    print(
        f"wrote {MANIFEST_PATH} ({len(manifest['tables'])} tables, "
        f"schema_version {manifest['schema_version']})"
    )
